name       : mpc-qt
version    : 18.03
release    : 1
source     :
    - https://github.com/cmdrkotori/mpc-qt/archive/v18.03.tar.gz : ae381ec5472daceb4c3907280cc5b423d7304428093ecc45789640d577e97c1d
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Media Player Classic Qute Theater
description: |
    Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(mpv)
setup      : |
    %patch -p1 < $pkgfiles/mpc-qt-Qt511.patch

    %qmake PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
