name       : mpc-qt
version    : '23.02'
release    : 7
source     :
    - https://github.com/mpc-qt/mpc-qt/archive/refs/tags/v23.02.tar.gz : c7bb48e53cf43e6705e67ae7de598d50f442ea73131d17142ea027042befd14c
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Media Player Classic Qute Theater
description: |
    Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(mpv)
    - pkgconfig(xcb)
setup      : |
    %qmake MPCQT_VERSION=$version PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
